[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
log_cli = true
log_cli_level = INFO
addopts = -v --tb=short

markers = 
    unit: fast unit tests, no external dependencies
    slow: slow tests, takes long to run
    ollama: calls ollama for testing
    chroma: hits the vector database for testing
    api: test fast api endpoints

filterwarnings = ignore::DeprecationWarning